version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - ./work:/home/abhishek0010/work
    container_name: jupyter_notebook
    command: "start-notebook.sh --NotebookApp.token="
    networks:
      - reverse_proxy_nw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis.rule=Host(`jupyter.abhishek0010.in`)"
      - "traefik.http.routers.redis.tls=true"
      #- "traefik.tcp.routers.redis.entrypoints=redis"
      - "traefik.http.services.redis.loadbalancer.server.port=8888"
      #- "traefik.tcp.routers.redis.service=redis"
networks:
  reverse_proxy_nw:
    external: true
